version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      - redis
    command: poetry run celery -A app.tasks worker --loglevel=INFO
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
